language: ruby
rvm:
- ruby-head
- 2.5.0
- 2.4.3
- 2.3.6
- 2.2.8
- 2.1.10
matrix:
  allow_failures:
  - rvm: 2.2.8
bundler_args: "--without development"
script:
- bundle exec rspec
addons:
  apt:
    packages:
    - ghostscript
    - poppler-utils
