language: ruby
rvm:
  - ruby-head
  - 2.6.1
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.2.10
  - 2.1.10
matrix:
  allow_failures:
  - rvm: 2.2.10
bundler_args: "--without development"
script:
- bundle exec rspec
addons:
  apt:
    packages:
    - ghostscript
    - poppler-utils
