language: ruby
rvm:
- ruby-head
- 2.4.1
- 2.3.3
- 2.2.7
- 2.1.10
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: 2.4.1
  - rvm: 2.3.3
  - rvm: 2.2.7
bundler_args: "--without development"
script:
- bundle exec rspec
addons:
  apt_packages:
    poppler-utils