language: ruby
rvm:
  - ruby-head
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
bundler_args: "--without development"
script:
  - sudo sed -i '/PDF/d' /etc/ImageMagick-6/policy.xml
  - bundle exec rspec
addons:
  apt:
    packages:
    - ghostscript
    - poppler-utils
